FROM bioconductor/bioconductor_docker:devel
WORKDIR /app
COPY requirements.txt /app
RUN pip3 --version
RUN python3 --version
RUN pip show setuptools
RUN apt-get update \
		&& python3 -m pip install --upgrade pip==23.0.1 \
		&& pip3 install -r requirements.txt \
		## to remove side-effects of apt-get update \
		&& apt-get clean \
		&& rm -rf /var/lib/apt/lists/*
RUN R -e "install.packages('snow')"
RUN R -e "install.packages('SoupX')"
RUN R -e "BiocManager::install(c('DropletUtils', 'scDblFinder', 'scry'))"
WORKDIR /home/scanpy
EXPOSE 8888
CMD ["jupyter", "notebook", "--port=8888", "--ip=0.0.0.0", "--allow-root"]
